### ISSUE TITLE
TypedMap.Key is unintuitive

### ISSUE THREAD

**Issue by leadVisionary** [awslabs/swage#7]
Consider the following code

```
package software.amazon.swage.howto;

import software.amazon.swage.collection.TypedMap;
import software.amazon.swage.metrics.ContextData;
import software.amazon.swage.metrics.Metric;
import software.amazon.swage.metrics.MetricRecorder;

import java.time.Instant;
import java.util.Objects;

/**
 * This task shows how to write metrics using Swage.
 */
public final class WriteMetricsTask implements Runnable {
    /**
     * A Metric to write.
     */
    private static final Metric METRIC = Metric.define("Cool");
    /**
     * A value for the Metric.
     */
    private static final Number NUMBER = 42;
    /**
     * that does the recording.
     */
    private final MetricRecorder recorder;
    /**
     * the ContextData that will be recorded from.
     */
    private final ContextData data;

    /**
     * constructor.
     * @param r should not be null.
     * @param data should not be null.
     */
    WriteMetricsTask(final MetricRecorder r,
                     final ContextData data) {
        this.recorder = Objects.requireNonNull(r);
        this.data = Objects.requireNonNull(data);
    }

    @Override
    public void run() {
        final TypedMap c = data
                .with(TypedMap.key("StartTime", String.class),
                        Long.valueOf(Instant.now().toEpochMilli()).toString())
                .build();
        final MetricRecorder.Context context = recorder.context(c);
        context.record(METRIC, NUMBER, null, Instant.now());
    }
}

```

with a test:

```
package software.amazon.swage.howto;

import org.junit.Before;
import org.junit.Test;
import org.mockito.ArgumentCaptor;

import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import software.amazon.swage.collection.TypedMap;
import software.amazon.swage.metrics.ContextData;
import software.amazon.swage.metrics.MetricRecorder;

import static org.junit.Assert.*;
import static org.mockito.BDDMockito.*;

public class WriteMetricsTaskTest {
    @Mock MetricRecorder recorder;
    @Mock ContextData data;
    @Captor ArgumentCaptor<TypedMap> captor;
    WriteMetricsTask toTest;


    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
        given(recorder.context(captor.capture())).willCallRealMethod();
        toTest = new WriteMetricsTask(recorder, data);
    }

    @Test
    public void canWriteMetrics() {
        toTest.run();
        final TypedMap captured = captor.getValue();
        verify(recorder).context(captured);
        assertTrue(captured.containsKey(TypedMap.key("StartTime", String.class)));
    }
}
```

That test fails. The assertion is false. Looking at the JavaDoc for TypedMap.Key seems to imply this was intentional.

Why would anyone find that usable? What would the intended usage look like here?

**Comment by jerpowers** [comment]
Yes this is intentional.  See javadoc on the TypedMap.

"* Uses of the map are expected to define the keys they use up-front for their
 * particular domain, using data only for those well defined keys.  Keys are
 * specific to the usage for a TypedMap, arbitrarily creating new keys is
 * discouraged."

In your example, you would have a key for StartTime defined once, and accessible to whatever needs to know about StartTime in the map.  The unit test would then reference the key object, not try to create a new one.  Uniqueness of keys are defined by key objects, not by string names.

**Comment by leadVisionary** [comment]
So if I want new keys, should I be creating a new implementation of TypedMap?

When I want to check that my map contains something, does that mean the Key needs to be accessible in some global registry of keys, a la 

`Container.SOME_KEY? `

I guess what I'm driving at is  why doesn't `TypedMap.Key` implement `equals` and `hashCode` if it's meant to be stored in a map?

https://stackoverflow.com/questions/2265503/why-do-i-need-to-override-the-equals-and-hashcode-methods-in-java

**Comment by jerpowers** [comment]
If you want new keys, you define new keys.  But yes they have to be accessible from everywhere you need to reference the values stored under the key.  Usually there will be some set of predefined keys, similar to an enum definition.  You shouldn't need new implementations of TypedMap unless there is some unique implementation type you want (similar to any other interface).

>  why doesn't TypedMap.Key implement equals and hashCode if it's meant to be stored in a map?

Because TypedMap is not the same as the Map collection.  The key is meant to be stored in a TypedMap, not in a Map.  Again, see the javadoc - it's not quite the same contract as Map.  In the case of TypedMap keys, equals is identity equals, which is the same as default object equals.

You can think of a TypedMap similar to an EnumMap or IdentityMap, but where the key also contains information on the type of object stored under the key.

**Comment by leadVisionary** [comment]
I found a way out of the corner I was in with a couple of utility methods:

```
/**
     * convenience method to see if a context has a key defined.
     * @param context to check for value
     * @param name the key name you're looking for
     * @return true if some key like it is there
     */
    private static boolean hasKeyNamed(final TypedMap context, final String name) {
        return context.keySet()
                .parallelStream()
                .map(TypedMap.Key::toString)
                .anyMatch(s -> s.equalsIgnoreCase(name));
    }

    /**
     * convenience method to retrieve the value for a context with a named key.
     * @param context to get the value from
     * @param name the key name you're looking for
     * @return the value you
     */
    private static String getValueForKeyNamed(final TypedMap context, final String name) {
        if (!hasKeyNamed(context, name)) {
            return "";
        }
        return context.stream()
                .filter(e -> e.getKey().name.equalsIgnoreCase(name))
                .findAny()
                .get()
                .getValue()
                .toString();
    }
```

Since the right primitives are exposed to basically check the key's `name` and `valueType` (I glanced over but didn't realize that these are public, not private fields), if you need this kind of uncommon use case you can figure out how to get what you want. 

If this comes up often in the future, it may be worth considering adding these or a variant to `TypedMap` directly.
